import = [
  "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
]


[env]
TERM = "xterm-256color"

[window]
padding.x = 14
padding.y = 14

decorations = "Buttonless"

opacity = 0.9
blur = true

startup_mode = "SimpleFullScreen"

option_as_alt = "both"

[font]
normal.family = "JetBrainsMono NFM"

size = 12

[cursor]
style = { shape = "Block", blinking = "On" }
