brew "starship"
brew "zoxide"
brew "eza"
brew "bat"
brew "fd"
brew "fzf"
brew "ripgrep"
brew "git"
brew "neovim"
brew "luacheck"
brew "tree-sitter-cli"
brew "postgresql@18", link: true
brew "pgformatter"
brew "zsh-autosuggestions"
brew "zsh-vi-mode"
brew "zsh-fast-syntax-highlighting"
cask "ghostty"
